export const enTrans = {
  "homeC": "Do they know that great things of this sort soften the soul from the least nice. Some cookies are snacks, some leave it as low as some excepteur, are a bit nice. Let the exceptioneur be willing to be taken to task, to shun employment and be betrayed by employment. It is irure labors toils that manufacturers must condemn to task pain does not result in nothing.",
  "logOut": "LOG OUT",
  "menuHome": "Home",
  "menuAbout": "About",
  "menuContact": "Contact",
  "menuCart": "Cart [{{ quantity }}]",
  "aboutTitle": "This is About Component",
  "contactTitle": "This is Contact Component",
  "contactContent": "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",
  "aboutContent": "They forsake nothing but our services. He wants the pain to be a job for the hard work, they are the smallest of the labors, they shun him for being very successful. Great services resultant from the pleasure of labor. Proident criticizes the team. This means that it is enhanced by hard work, and that it does not give the soul the pleasure of the Home. The main responsibility of blacks is to achieve, they will come to mind that they should be criticized for their hard work. In the big game the services are owned by the least of those who criticize the EU, who will provide no opportunities for it. The blame blinds the guy who doesn't want to fall back on time. Exercise as low as anyone to abandon. I give pain to the elite to do the exercise, but I want to do it for the pleasure of the game. They will not be responsible for the consequences of their efforts unless they provide the exceptioneur who craves to shun the labor and they are to shun such a great irure. For, however, any labors of this kind. No labor will come out of the soul of labor as low as the fault of any resultant labor. He tasked the team with being comfortable with objectives. It's the kind of thing that's out there, and it softens them."
}
