export const viTrans = {
  "homeC": "Họ có biết rằng những điều tuyệt vời kiểu này sẽ làm mềm tâm hồn khỏi những điều kém tốt đẹp nhất. Một số bánh quy là đồ ăn nhẹ, một số để nó thấp như một số loại bánh ngoại tệ, là một chút tốt. Hãy để cho người ngoại lệ sẵn sàng thực hiện nhiệm vụ, xa lánh việc làm và bị phản bội bởi việc làm. Việc các nhà sản xuất phải lên án để làm việc đau đớn không mang lại kết quả gì.",
  "logOut": "Đăng xuất",
  "menuHome": "Trang chủ",
  "menuAbout": "Giới thiệu",
  "menuContact": "Liên hệ",
  "menuCart": "Giỏ hàng [{{ quantity }}]",
  "aboutTitle": "Đây là Trang Giới thiệu",
  "contactTitle": "Đây là trang Liên Hệ",
  "contactContent": "Có rất nhiều biến thể của các đoạn văn của Lorem Ipsum có sẵn, nhưng phần lớn đã bị thay đổi dưới một số hình thức, bởi sự hài hước được đưa vào hoặc các từ ngẫu nhiên trông thậm chí không đáng tin một chút. Nếu bạn định sử dụng một đoạn văn của Lorem Ipsum, bạn cần chắc chắn rằng không có bất kỳ điều gì đáng xấu hổ ẩn ở giữa văn bản. Tất cả các trình tạo Lorem Ipsum trên Internet đều có xu hướng lặp lại các phần được xác định trước khi cần thiết, khiến đây trở thành trình tạo thực sự đầu tiên trên Internet. Nó sử dụng một từ điển hơn 200 từ Latinh, kết hợp với một số cấu trúc câu mô hình, để tạo ra Lorem Ipsum trông hợp lý. Do đó, Lorem Ipsum được tạo ra luôn không bị lặp lại, có sự hài hước hoặc các từ không đặc trưng, v.v.",
  "aboutContent": "Họ không từ bỏ gì ngoài các dịch vụ của chúng tôi. Anh muốn nỗi đau là một công việc cho những công việc khó khăn, họ là những người nhỏ nhất trong những lao động, họ xa lánh anh vì đã rất thành công. Dịch vụ tuyệt vời là kết quả của niềm vui lao động. Tự tin chỉ trích đội. Điều này có nghĩa là nó được nâng cao bởi công việc khó khăn, và nó không mang lại cho tâm hồn của gia đình niềm vui. Trách nhiệm chính của người da đen là phải đạt được, họ sẽ nghĩ rằng họ nên bị chỉ trích vì đã làm việc chăm chỉ. Trong trò chơi lớn, các dịch vụ thuộc sở hữu của ít nhất trong số những người chỉ trích EU, những người sẽ không cung cấp cơ hội cho nó. Sự đổ lỗi làm mù quáng anh chàng không muốn lùi thời gian. Tập thể dục thấp như bất cứ ai để bỏ rơi. Tôi dành sự đau đớn cho những người ưu tú để thực hiện bài tập, nhưng tôi muốn làm điều đó vì niềm vui của trò chơi. Họ sẽ không chịu trách nhiệm về hậu quả của những nỗ lực của họ trừ khi họ cung cấp cho người ngoại lệ, những người khao khát trốn tránh lao động và họ sẽ trốn tránh một sự bất bình lớn như vậy. Tuy nhiên, đối với bất kỳ lao động nào thuộc loại này. Không có lao động nào thoát ra khỏi linh hồn của lao động thấp như lỗi của bất kỳ kết quả lao động nào. Anh ấy giao nhiệm vụ cho cả đội phải thoải mái với các mục tiêu. Đó là loại thứ ngoài kia, và nó làm mềm chúng."
}
