import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/navbar'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Artana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/no_bank.png" />
      </Head>

      <main className={styles.main}>
        <Navbar />
      </main>
    </div>
  )
}

export default Home
