import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Artana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/no_bank.png" />
      </Head>

      <main className={styles.main}>
      </main>
    </>
  )
}

export default Home
