import type { NextPage } from 'next'
import Head from 'next/head'
import '../i18n'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Artana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/no_bank.png" />
      </Head>
      <main className="main" />
    </>
  )
}

export default Home
